// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpv_3M9r_0FXbBNOlxJrFpTRTAiu2psM',
    appId: '1:736016767042:web:233b83beee6376252a75db',
    messagingSenderId: '736016767042',
    projectId: 'chess-game-8dd9b',
    authDomain: 'chess-game-8dd9b.firebaseapp.com',
    storageBucket: 'chess-game-8dd9b.firebasestorage.app',
    measurementId: 'G-B0JPM4HPW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCW2oWXbWIUx5gPNvM5Q2RWbXNJF_x1OY',
    appId: '1:736016767042:android:c462f8903e4ad3002a75db',
    messagingSenderId: '736016767042',
    projectId: 'chess-game-8dd9b',
    storageBucket: 'chess-game-8dd9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQOx4uRmbsQ3Dh75FYbJyrWyFL_WM5Ks8',
    appId: '1:736016767042:ios:4ee06639c94a42ef2a75db',
    messagingSenderId: '736016767042',
    projectId: 'chess-game-8dd9b',
    storageBucket: 'chess-game-8dd9b.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQOx4uRmbsQ3Dh75FYbJyrWyFL_WM5Ks8',
    appId: '1:736016767042:ios:4ee06639c94a42ef2a75db',
    messagingSenderId: '736016767042',
    projectId: 'chess-game-8dd9b',
    storageBucket: 'chess-game-8dd9b.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgpv_3M9r_0FXbBNOlxJrFpTRTAiu2psM',
    appId: '1:736016767042:web:a4d0c02dce8ca4e62a75db',
    messagingSenderId: '736016767042',
    projectId: 'chess-game-8dd9b',
    authDomain: 'chess-game-8dd9b.firebaseapp.com',
    storageBucket: 'chess-game-8dd9b.firebasestorage.app',
    measurementId: 'G-FQK9LYYY8V',
  );
}
